In [75]:
import pandas as pd
import numpy as np

In [76]:
data=pd.read_excel("Linear Regression.xlsx")
data.head(2)

price  sqft_living  bedrooms  bathrooms  floors
0  221900         1180         3       1.00     1.0
1  538000         2570         3       2.25     2.0

In [77]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   price        21613 non-null  int64  
 1   sqft_living  21613 non-null  int64  
 2   bedrooms     21613 non-null  int64  
 3   bathrooms    21613 non-null  float64
 4   floors       21613 non-null  float64
dtypes: float64(2), int64(3)
memory usage: 844.4 KB


In [78]:
data.dtypes

price            int64
sqft_living      int64
bedrooms         int64
bathrooms      float64
floors         float64
dtype: object

In [79]:
data.drop_duplicates()

price  sqft_living  bedrooms  bathrooms  floors
0      221900         1180         3       1.00     1.0
1      538000         2570         3       2.25     2.0
2      180000          770         2       1.00     1.0
3      604000         1960         4       3.00     1.0
4      510000         1680         3       2.00     1.0
...       ...          ...       ...        ...     ...
21608  360000         1530         3       2.50     3.0
21609  400000         2310         4       2.50     2.0
21610  402101         1020         2       0.75     2.0
21611  400000         1600         3       2.50     2.0
21612  325000         1020         2       0.75     2.0

[21347 rows x 5 columns]

In [80]:
data.isna().sum()

price          0
sqft_living    0
bedrooms       0
bathrooms      0
floors         0
dtype: int64

In [82]:
data.columns

Index(['price', 'sqft_living', 'bedrooms', 'bathrooms', 'floors'], dtype='object')

In [134]:
X=data.iloc[:,1:2]
y=data.iloc[:,:1]

In [135]:
X.head(2)

sqft_living
0         1180
1         2570

In [136]:
y.head(2)

price
0  221900
1  538000

In [137]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_squared_error

In [138]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [139]:
Lin_Reg=LinearRegression()

In [140]:
Lin_Reg

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [141]:
X_train.head(2)

sqft_living
1468          1390
15590         1450

In [142]:
X_test.head(2)

sqft_living
17384         1430
722           4670

In [143]:
y_train.head(2)

price
1468   400000
15590  430000

In [144]:
y_test.head(2)

price
17384   297000
722    1578000

In [145]:
Lin_Reg.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [148]:
ypred=Lin_Reg.predict(X_test)
ypred

array([[ 360116.30918286],
       [1261900.99730684],
       [ 362899.59525731],
       ...,
       [ 560512.90654374],
       [ 374032.73955514],
       [ 329500.16236383]])

In [152]:
from sklearn.metrics import r2_score,mean_squared_error
RMSE=np.sqrt(mean_squared_error(y_test,ypred))
r_square=r2_score(y_test,ypred)*100
print("Root mean square error is......",RMSE)
print("r square value is......",r_square,"%")

Root mean square error is...... 264896.2296616816
r square value is...... 48.8899283822523 %


# Conclusion

1. R-square value is 0.48 suggesting that only about 48% of the variance in the target variable i.e. price can be explained by the independent variable area of living.

2. Root mean square error is very high for the model suggesting that a large error exist in between the predicted value and the actual values of the target variable (price).

**Not a good regression fit**

In [157]:
# Generating other models with respect to other Independent Variables - 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_squared_error
def LR(X,y):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)
    lin_reg=LinearRegression()
    lin_reg.fit(X_train,y_train)
    ypred=lin_reg.predict(X_test)
    print(ypred) 
    RMSE=np.sqrt(mean_squared_error(y_test,ypred))
    r_square=r2_score(y_test,ypred)*100
    print("Root mean square error is......",RMSE)
    print("r square value is......",r_square,"%")

In [160]:
print("Analysing Regression between price & bedrooms:")
LR(data.iloc[:,2:3], data.iloc[:,:1])

Analysing Regression between price & bedrooms:
[[374793.31134634]
 [617650.27612113]
 [374793.31134634]
 ...
 [496221.79373374]
 [496221.79373374]
 [496221.79373374]]
Root mean square error is...... 353950.7410998196
r square value is...... 8.748379078274871 %


# Conclusion - 

1. R-square value is 0.0874 suggesting that only about 8% of the variance in the target variable i.e. price can be explained by the independent variable number of bedrooms.

2. Root mean square error is very high for the model suggesting that a large error exist in between the predicted value and the actual values of the target variable (price).

**Not a good regression fit**

In [161]:
print("Analysing Regression between price & bathrooms:")
LR(data.iloc[:,3:4], data.iloc[:,:1])

Analysing Regression between price & bathrooms:
[[388089.1191871 ]
 [822051.26818571]
 [202105.34104484]
 ...
 [636067.49004345]
 [450083.71190119]
 [264099.93375893]]
Root mean square error is...... 314385.49465499417
r square value is...... 28.008713303193346 %


# Conclusion - 

1. R-square value is 0.28 suggesting that only about 28% of the variance in the target variable i.e. price can be explained by the independent variable number of bathrooms.

2. Root mean square error is very high for the model suggesting that a large error exist in between the predicted value and the actual values of the target variable (price).

**Not a good regression fit**

In [162]:
print("Analysing Regression between price & floors:")
LR(data.iloc[:,4:], data.iloc[:,:1])

Analysing Regression between price & floors:
[[800986.15002601]
 [627522.16188257]
 [454058.17373912]
 ...
 [540790.16781085]
 [454058.17373912]
 [454058.17373912]]
Root mean square error is...... 358249.01149854274
r square value is...... 6.518658268569688 %


# Conclusion - 

1. R-square value is 0.06 suggesting that only about 6% of the variance in the target variable i.e. price can be explained by the independent variable number of floors.

2) Root mean square error is very high for the model suggesting that a large error exist in between the predicted value and the actual values of the target variable (price).

**Not a good regression fit**

# Perofrming  Multiple Regression(Taking all the columns as Independent Variable against the Dependent Variable(Price) - 

In [163]:
print("Analysing Multiple Regression between price & rest of the factors from the given dataset:")
LR(data.iloc[:,1:5], data.iloc[:,:1])

Analysing Multiple Regression between price & rest of the factors from the given dataset:
[[ 418082.2070007 ]
 [1306707.47771871]
 [ 409588.1373233 ]
 ...
 [ 583468.89595792]
 [ 373227.82730922]
 [ 321070.6451827 ]]
Root mean square error is...... 260340.45808582992
r square value is...... 50.63282621650447 %


# Conclusion - 

1. R-square value is 0.5 suggesting that only about 50% or half of the variance in the target variable i.e. price can be explained by the independent variables area of living, number of bedrooms,number of bathrooms and number of floors.

2. Root mean square error is very high for the model suggesting that a large error exist in between the predicted value and the actual values of the target variable (price).

**Not a good regression fit**